codecov:
  require_ci_to_pass: true

ignore:
  - ".guardrails/**"
  - ".deepsource.toml"
  - ".qlty/**"
  - ".github/dependabot.yml"

flags:
  repo:
    paths:
      - build/

coverage:
  status:
    project:
      default:
        target: 100.0%
        threshold: 0%
    patch:
      default:
        target: 100.0%
        threshold: 0%
